import React from 'react';
import { FlexWidget, SvgWidget } from 'react-native-android-widget';

import { quickAddTileSvg } from './dodone-mark';

const TILE_SVG = quickAddTileSvg();

/**
 * 1x1 home-screen widget — the DoDone mark on an indigo squircle with a "+"
 * badge, like Todoist's add-task button. Drawn as a single inline SVG so it
 * stays crisp at whatever size the launcher gives the cell.
 *
 * Tapping it opens the translucent QuickAddActivity (via the dedicated
 * `dodoneadd://open` scheme) so a quick-add sheet floats over the home screen
 * instead of launching the main app. See QuickAddActivity.kt (generated by
 * plugins/withQuickAddActivity.js) and quick-add-root.tsx.
 */
export function QuickAddWidget() {
  return (
    <FlexWidget
      style={{
        height: 'match_parent',
        width: 'match_parent',
        justifyContent: 'center',
        alignItems: 'center',
      }}
      clickAction="OPEN_URI"
      clickActionData={{ uri: 'dodoneadd://open' }}
    >
      <SvgWidget
        svg={TILE_SVG}
        style={{ height: 'match_parent', width: 'match_parent' }}
      />
    </FlexWidget>
  );
}
