import React from 'react';
import { FlexWidget, IconWidget } from 'react-native-android-widget';

/**
 * 1x1 home-screen widget — a single indigo square with a white "+", like
 * Todoist's add-task widget. Tapping it opens the translucent QuickAddActivity
 * (via the dedicated `dodoneadd://open` scheme) so a quick-add sheet floats over
 * the home screen instead of launching the main app. See QuickAddActivity.kt
 * (generated by plugins/withQuickAddActivity.js) and quick-add-root.tsx.
 */
export function QuickAddWidget() {
  return (
    <FlexWidget
      style={{
        height: 'match_parent',
        width: 'match_parent',
        borderRadius: 20,
        backgroundColor: '#6366f1',
        justifyContent: 'center',
        alignItems: 'center',
      }}
      clickAction="OPEN_URI"
      clickActionData={{ uri: 'dodoneadd://open' }}
    >
      <IconWidget
        font="material"
        icon="add"
        size={32}
        style={{ color: '#ffffff' }}
      />
    </FlexWidget>
  );
}
