import React from 'react';
import { FlexWidget, SvgWidget } from 'react-native-android-widget';

import { quickAddTileSvg } from './dodone-mark';

const TILE_SVG = quickAddTileSvg();

/** The tile artwork's own canvas, and the corner radius on it. */
const SVG_CANVAS = 120;
const SVG_CORNER = 28;

/**
 * Side to draw at when the launcher reports no size for the cell. The options
 * bundle can be empty on the very first update from some launchers, and a
 * zero-sized tile is an invisible one.
 */
const FALLBACK_SIDE_DP = 56;

/**
 * 1x1 home-screen widget — the DoDone mark on an indigo squircle with a "+"
 * badge, like Todoist's add-task button. Drawn as a single inline SVG so it
 * stays crisp at whatever size the launcher gives the cell.
 *
 * The squircle is painted TWICE, on purpose: the SVG draws it, and
 * the `FlexWidget` behind it fills the same square with flat indigo. `SvgWidget`
 * hands the string to AndroidSVG and swallows a parse failure with nothing but a
 * `printStackTrace`, so a tile that leans on it alone has a silent path to fully
 * transparent — which on a home screen is not a broken tile, it's no tile. The
 * painted square costs one view and guarantees something visible and tappable.
 *
 * Sized to a centred square of `min(width, height)` rather than `match_parent`:
 * a launcher cell is taller than it is wide, and the artwork is square, so
 * matching the parent would letterbox the SVG inside its own background.
 *
 * Tapping it opens the translucent QuickAddActivity (via the dedicated
 * `dodoneadd://open` scheme) so a quick-add sheet floats over the home screen
 * instead of launching the main app. See QuickAddActivity.kt (generated by
 * plugins/withQuickAddActivity.js) and quick-add-root.tsx.
 */
export function QuickAddWidget({
  width,
  height,
}: {
  /** Cell width in dp, from `widgetInfo`. */
  width?: number;
  /** Cell height in dp, from `widgetInfo`. */
  height?: number;
}) {
  const cell = Math.min(width ?? 0, height ?? 0);
  const side = cell > 0 ? cell : FALLBACK_SIDE_DP;

  return (
    <FlexWidget
      style={{
        height: 'match_parent',
        width: 'match_parent',
        justifyContent: 'center',
        alignItems: 'center',
      }}
      clickAction="OPEN_URI"
      clickActionData={{ uri: 'dodoneadd://open' }}
    >
      <FlexWidget
        style={{
          width: side,
          height: side,
          borderRadius: (side * SVG_CORNER) / SVG_CANVAS,
          backgroundColor: '#6366f1',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <SvgWidget svg={TILE_SVG} style={{ width: side, height: side }} />
      </FlexWidget>
    </FlexWidget>
  );
}
