// The curated Phosphor set offered in DoDone's project icon picker.
// Groups mirror the emoji catalogue so the two tabs read the same way.
//
// **A name appears in exactly one group.** The picker renders a flat, unheaded
// grid the moment anything narrows the list, and keys those cells by name
// alone — so the same icon in two groups collides on a React key there. Pick
// the group a user would look in first and use a sibling icon for the other
// reading (Work has `buildings`, Travel has `city`; Nature has `snowflake`,
// Food has `jar`).
export const GROUPS = [
  {
    id: "work",
    label: "Work",
    icons: [
      ["briefcase", "Briefcase", "work job business"],
      ["briefcase-metal", "Business", "case corporate"],
      ["buildings", "Office", "building company"],
      ["building-office", "Workplace", "office block"],
      ["chart-bar", "Chart", "report data metrics"],
      ["chart-line", "Trends", "graph analytics"],
      ["chart-pie", "Breakdown", "share split data"],
      ["presentation-chart", "Presentation", "deck slides pitch"],
      ["trend-up", "Growth", "chart up revenue"],
      ["note-pencil", "Notes", "write memo draft"],
      ["clipboard-text", "Clipboard", "list checklist admin"],
      ["list-checks", "Checklist", "todo tasks tick"],
      ["folders", "Files", "folder archive"],
      ["archive", "Archive", "store old box"],
      ["push-pin", "Pin", "important sticky"],
      ["calendar-blank", "Calendar", "schedule planning"],
      ["calendar-check", "Booked", "confirmed appointment"],
      ["calendar-dots", "Schedule", "agenda diary"],
      ["alarm", "Deadline", "alarm time urgent"],
      ["timer", "Timer", "stopwatch tracking"],
      ["hourglass", "Waiting", "pending blocked time"],
      ["target", "Goal", "target okr focus"],
      ["crosshair", "Focus", "aim precision"],
      ["rocket-launch", "Launch", "ship release startup"],
      ["gear", "Operations", "settings process"],
      ["lightbulb", "Idea", "brainstorm concept"],
      ["strategy", "Strategy", "plan chess tactics"],
      ["handshake", "Meeting", "client partner deal"],
      ["envelope-simple", "Email", "inbox mail message"],
      ["paper-plane-tilt", "Send", "sent outbox"],
      ["phone", "Calls", "phone ring"],
      ["toolbox", "Toolbox", "maintenance utilities"],
      ["kanban", "Board", "backlog columns sprint"],
      ["tree-structure", "Org chart", "hierarchy structure"],
      ["users-four", "Team", "staff colleagues"],
      ["megaphone", "Announcements", "marketing promote"],
      ["seal-check", "Approved", "verified sign off"],
      ["signature", "Signing", "contract sign"],
      ["stamp", "Admin", "approve paperwork"],
      ["printer", "Printing", "paper print"],
      ["desk", "Desk", "workspace office"],
      ["office-chair", "Seat", "chair desk office"],
    ],
  },
  {
    id: "study",
    label: "Study",
    icons: [
      ["books", "Books", "reading library study"],
      ["book-open", "Reading", "book chapter"],
      ["book-bookmark", "Textbook", "reference study"],
      ["book-open-text", "Studying", "revision notes"],
      ["graduation-cap", "School", "university course degree"],
      ["student", "Student", "pupil learner"],
      ["chalkboard-teacher", "Teaching", "class lesson tutor"],
      ["chalkboard", "Lessons", "class board"],
      ["exam", "Exams", "test paper assessment"],
      ["pencil-simple", "Writing", "essay draft author"],
      ["pencil-ruler", "Drafting", "design sketch plan"],
      ["highlighter", "Highlights", "marker notes"],
      ["eraser", "Corrections", "rubber undo"],
      ["brain", "Learning", "brain think memory"],
      ["microscope", "Research", "science lab"],
      ["flask", "Experiment", "lab test chemistry"],
      ["test-tube", "Lab", "sample chemistry"],
      ["atom", "Physics", "science atom"],
      ["dna", "Biology", "genetics science"],
      ["calculator", "Maths", "numbers sums"],
      ["math-operations", "Arithmetic", "sums numbers"],
      ["sigma", "Statistics", "sum maths"],
      ["planet", "Astronomy", "space explore telescope"],
      ["globe-hemisphere-west", "Languages", "globe world"],
      ["translate", "Translation", "language words"],
      ["backpack", "Backpack", "school class"],
      ["code", "Code", "dev programming"],
      ["terminal-window", "Terminal", "shell command dev"],
      ["notebook", "Notebook", "journal notes"],
      ["article", "Article", "paper writing"],
      ["scroll", "History", "old document"],
      ["certificate", "Certificate", "qualification award"],
      ["lectern", "Lecture", "talk speaking"],
    ],
  },
  {
    id: "home",
    label: "Home",
    icons: [
      ["house", "Home", "house personal"],
      ["house-line", "House", "property home"],
      ["house-simple", "Flat", "apartment home"],
      ["armchair", "Living room", "sofa lounge furniture"],
      ["couch", "Sofa", "lounge seating"],
      ["bed", "Bedroom", "bed sleep"],
      ["dresser", "Dresser", "drawers furniture"],
      ["lamp", "Lamp", "light table"],
      ["lamp-pendant", "Lighting", "ceiling light"],
      ["shower", "Bathroom", "shower clean"],
      ["bathtub", "Bath", "bathroom soak"],
      ["toilet", "Toilet", "bathroom loo"],
      ["toilet-paper", "Supplies", "household essentials"],
      ["towel", "Towels", "linen bathroom"],
      ["broom", "Cleaning", "chores tidy"],
      ["spray-bottle", "Spray", "cleaner surfaces"],
      ["washing-machine", "Laundry", "washing clothes"],
      ["hand-soap", "Washing up", "soap dishes clean"],
      ["coat-hanger", "Wardrobe", "clothes closet"],
      ["hammer", "DIY", "hammer repair build"],
      ["screwdriver", "Fixing", "repair tools"],
      ["pipe-wrench", "Plumbing", "pipes leak"],
      ["paint-roller", "Decorating", "paint walls"],
      ["paint-brush-household", "Painting", "decorating walls"],
      ["ladder", "Ladder", "climb reach diy"],
      ["potted-plant", "Plants", "houseplant garden water"],
      ["package", "Moving", "box packing storage"],
      ["key", "Keys", "access landlord rent"],
      ["door", "Doors", "room entry"],
      ["door-open", "Entry", "open doorway"],
      ["receipt", "Bills", "receipt utilities admin"],
      ["stairs", "Stairs", "steps upstairs"],
      ["garage", "Garage", "car storage"],
      ["oven", "Oven", "kitchen appliance"],
      ["chair", "Chair", "seat furniture"],
      ["stool", "Stool", "seat furniture"],
      ["rug", "Rug", "carpet floor"],
      ["trash", "Rubbish", "bin waste recycling"],
      ["lockers", "Storage", "cupboard locker"],
    ],
  },
  {
    id: "people",
    label: "People",
    icons: [
      ["users-three", "Family", "household kids parents"],
      ["users", "Group", "people friends"],
      ["user", "Person", "someone me friend"],
      ["user-circle", "Profile", "account avatar"],
      ["user-plus", "New contact", "add invite"],
      ["baby", "Baby", "child kids newborn"],
      ["baby-carriage", "Parenting", "pram child"],
      ["hand-waving", "Catch-ups", "hello friends social"],
      ["hands-clapping", "Applause", "praise well done"],
      ["chat-circle-dots", "Conversations", "chat talk message"],
      ["chats-circle", "Group chat", "discussion thread"],
      ["chat-text", "Messages", "sms text reply"],
      ["heart", "Love", "heart partner relationship"],
      ["hand-heart", "Care", "kindness support"],
      ["hands-praying", "Thanks", "gratitude pray"],
      ["confetti", "Celebration", "party event fun"],
      ["gift", "Gifts", "present birthday"],
      ["cake", "Birthdays", "cake anniversary"],
      ["balloon", "Party", "celebrate event"],
      ["envelope-open", "Cards", "letter note thanks"],
      ["address-book", "Contacts", "people directory"],
      ["identification-card", "ID", "identity card badge"],
      ["dog", "Dog", "pet puppy walk"],
      ["cat", "Cat", "pet kitten"],
      ["paw-print", "Pets", "animal vet"],
      ["rabbit", "Rabbit", "pet bunny"],
      ["horse", "Horse", "riding stable"],
      ["cow", "Cow", "farm cattle"],
      ["smiley", "Mood", "happy feelings"],
      ["person-arms-spread", "Someone", "person people"],
      ["peace", "Peace", "calm harmony"],
    ],
  },
  {
    id: "health",
    label: "Health",
    icons: [
      ["person-simple-run", "Running", "exercise cardio jog"],
      ["person-simple-walk", "Walking", "steps stroll"],
      ["person-simple-hike", "Hiking", "walk trail outdoors"],
      ["person-simple-tai-chi", "Meditation", "yoga calm mindful"],
      ["person-simple-bike", "Cycling", "bike ride"],
      ["person-simple-swim", "Swimming", "pool swim"],
      ["person-simple-ski", "Skiing", "snow winter sport"],
      ["person-simple-snowboard", "Snowboarding", "snow winter sport"],
      ["barbell", "Gym", "weights lifting strength"],
      ["boxing-glove", "Boxing", "fight sparring"],
      ["heartbeat", "Fitness", "health pulse"],
      ["soccer-ball", "Football", "soccer sport team"],
      ["basketball", "Basketball", "sport hoops"],
      ["tennis-ball", "Tennis", "sport racket"],
      ["football", "American football", "nfl sport"],
      ["volleyball", "Volleyball", "sport beach"],
      ["baseball", "Baseball", "sport bat"],
      ["ping-pong", "Table tennis", "pingpong sport"],
      ["golf", "Golf", "sport course"],
      ["bowling-ball", "Bowling", "sport alley"],
      ["hockey", "Hockey", "sport ice stick"],
      ["cricket", "Cricket", "sport bat"],
      ["swimming-pool", "Pool", "swim lengths"],
      ["stethoscope", "Doctor", "medical appointment"],
      ["pill", "Medication", "pills pharmacy"],
      ["prescription", "Prescription", "pharmacy repeat"],
      ["syringe", "Vaccination", "jab injection"],
      ["first-aid-kit", "First aid", "medical emergency"],
      ["bandaids", "Plasters", "injury cut"],
      ["tooth", "Dentist", "teeth appointment"],
      ["eyeglasses", "Optician", "eyes glasses test"],
      ["hospital", "Hospital", "medical clinic"],
      ["scales", "Weight", "balance measure"],
      ["thermometer", "Temperature", "fever illness"],
      ["wheelchair", "Accessibility", "mobility access"],
      ["footprints", "Steps", "walking count"],
      ["moon", "Sleep", "rest bedtime night"],
      ["bowl-food", "Eating well", "salad diet healthy"],
    ],
  },
  {
    id: "food",
    label: "Food",
    icons: [
      ["cooking-pot", "Cooking", "kitchen recipe meal"],
      ["chef-hat", "Recipes", "cook chef"],
      ["fork-knife", "Meals", "dinner eating restaurant"],
      ["knife", "Prep", "chop cooking"],
      ["bowl-steam", "Soup", "hot bowl noodles"],
      ["shopping-cart", "Groceries", "shopping supermarket"],
      ["basket", "Basket", "shopping shop"],
      ["carrot", "Vegetables", "veg greens"],
      ["pepper", "Spice", "chilli hot"],
      ["orange", "Fruit", "citrus healthy"],
      ["cherries", "Berries", "fruit summer"],
      ["avocado", "Avocado", "fruit brunch"],
      ["grains", "Grains", "rice pasta cereal"],
      ["bread", "Baking", "bread oven"],
      ["cheese", "Cheese", "dairy"],
      ["egg", "Breakfast", "eggs morning"],
      ["fish-simple", "Fish", "seafood dinner"],
      ["shrimp", "Seafood", "prawn shellfish"],
      ["hamburger", "Burgers", "fast food"],
      ["pizza", "Takeaway", "pizza delivery"],
      ["onigiri", "Sushi", "japanese rice"],
      ["popcorn", "Snacks", "cinema nibbles"],
      ["cookie", "Treats", "dessert sweet"],
      ["ice-cream", "Ice cream", "dessert summer"],
      ["popsicle", "Lollies", "ice dessert"],
      ["champagne", "Celebrating", "fizz toast"],
      ["wine", "Wine", "drinks evening"],
      ["beer-stein", "Beer", "pub drinks"],
      ["beer-bottle", "Bottles", "drinks beer"],
      ["martini", "Cocktails", "drinks bar"],
      ["brandy", "Spirits", "drinks whisky"],
      ["coffee", "Coffee", "cafe morning break"],
      ["coffee-bean", "Beans", "coffee roast"],
      ["tea-bag", "Tea", "brew drink"],
      ["pint-glass", "Pub", "beer drinks out"],
      ["jar", "Preserves", "jam storage pantry"],
      ["picnic-table", "Picnic", "outdoors lunch"],
      ["cheers", "Toast", "drinks celebrate"],
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icons: [
      ["airplane-tilt", "Flights", "plane travel trip"],
      ["airplane-takeoff", "Departure", "flight leaving"],
      ["airplane-landing", "Arrival", "flight landing"],
      ["suitcase-rolling", "Packing", "luggage suitcase trip"],
      ["suitcase-simple", "Luggage", "bag travel"],
      ["trolley-suitcase", "Baggage", "airport luggage"],
      ["map-trifold", "Trip planning", "map itinerary route"],
      ["map-pin", "Place", "location pin where"],
      ["compass", "Navigation", "direction find"],
      ["path", "Route", "journey way"],
      ["signpost", "Directions", "sign way"],
      ["road-horizon", "Road trip", "drive journey"],
      ["car", "Driving", "car road trip"],
      ["taxi", "Taxi", "cab ride"],
      ["jeep", "Off-road", "4x4 adventure"],
      // Not "transport": search matches substrings, so it makes a van a
      // result for "sport" alongside the whole Health group.
      ["van", "Van", "move haulage delivery"],
      ["bus", "Bus", "transit commute"],
      ["train", "Trains", "rail commute"],
      ["tram", "Tram", "transit rail"],
      ["subway", "Underground", "metro tube"],
      ["boat", "Ferry", "sea crossing"],
      ["sailboat", "Sailing", "boat sea"],
      ["anchor", "Harbour", "port boat"],
      ["bicycle", "Bike", "cycling commute"],
      ["motorcycle", "Motorbike", "ride bike"],
      ["scooter", "Scooter", "moped ride"],
      ["gas-pump", "Fuel", "petrol gas car"],
      ["charging-station", "Charging", "ev electric car"],
      ["ticket", "Tickets", "booking event entry"],
      ["island", "Holiday", "beach island vacation"],
      ["tree-palm", "Beach", "tropical holiday"],
      ["tent", "Camping", "tent outdoors"],
      ["campfire", "Campfire", "camping outdoors"],
      ["mountains", "Mountains", "hiking outdoors ski"],
      ["globe", "World", "international abroad"],
      ["city", "City", "urban skyline"],
      ["lighthouse", "Coast", "sea shore"],
      ["cable-car", "Cable car", "mountain lift"],
    ],
  },
  {
    id: "money",
    label: "Money",
    icons: [
      ["money", "Money", "cash savings budget"],
      ["money-wavy", "Cash", "notes spending"],
      ["cash-register", "Till", "sales shop"],
      ["credit-card", "Card", "payment spending credit"],
      ["contactless-payment", "Payments", "tap pay"],
      ["cardholder", "Cards", "wallet payment"],
      ["coins", "Savings", "coin invest pension"],
      ["coin", "Coin", "money change"],
      ["bank", "Bank", "account mortgage finance"],
      ["vault", "Vault", "safe secure savings"],
      ["wallet", "Wallet", "spending pocket"],
      ["piggy-bank", "Budget", "saving goal"],
      ["tip-jar", "Tips", "jar saving"],
      ["treasure-chest", "Reserves", "savings fund"],
      ["trend-down", "Expenses", "chart down costs"],
      ["chart-donut", "Allocation", "split breakdown"],
      ["tag", "Deals", "price sale"],
      ["tag-simple", "Price", "cost label"],
      ["seal-percent", "Discount", "sale offer"],
      ["invoice", "Invoices", "billing receipt"],
      ["hand-coins", "Income", "earnings paid"],
      ["hand-deposit", "Deposit", "pay in transfer"],
      ["hand-withdraw", "Withdrawal", "take out transfer"],
      ["currency-dollar", "Dollars", "usd money"],
      ["currency-gbp", "Pounds", "gbp sterling money"],
      ["currency-eur", "Euros", "eur money"],
      ["currency-btc", "Crypto", "bitcoin money"],
      ["percent", "Interest", "rate percentage"],
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icons: [
      ["plant", "Growing", "seedling start garden"],
      ["tree", "Tree", "garden outdoors nature"],
      ["tree-evergreen", "Evergreen", "pine forest"],
      ["flower", "Blossom", "flower spring"],
      ["flower-tulip", "Tulip", "flower spring"],
      ["flower-lotus", "Lotus", "flower calm"],
      ["clover", "Luck", "shamrock four leaf"],
      ["leaf", "Autumn", "leaves fall season"],
      ["acorn", "Acorn", "oak autumn"],
      ["cactus", "Cactus", "desert plant"],
      ["sun", "Sun", "summer weather morning"],
      ["sun-horizon", "Sunset", "dusk dawn evening"],
      ["sun-dim", "Daylight", "bright light"],
      ["moon-stars", "Night", "moon evening"],
      ["star", "Star", "favourite highlight special"],
      ["shooting-star", "Wish", "star night"],
      ["cloud", "Cloud", "sky overcast"],
      ["cloud-sun", "Weather", "cloud forecast"],
      ["cloud-rain", "Rain", "wet weather"],
      ["cloud-lightning", "Storm", "thunder weather"],
      ["cloud-snow", "Snow", "winter weather"],
      ["cloud-fog", "Fog", "mist weather"],
      ["rainbow", "Rainbow", "colour weather"],
      ["snowflake", "Winter", "snow cold season"],
      ["wind", "Wind", "breeze weather"],
      ["tornado", "Tornado", "storm weather"],
      ["umbrella", "Umbrella", "rain shelter"],
      ["drop", "Water", "drop hydration rain"],
      ["waves", "Sea", "wave ocean"],
      ["fire", "Hot", "fire streak urgent"],
      ["fish", "Aquarium", "fish pet tank"],
      ["butterfly", "Butterfly", "insect spring"],
      ["bug", "Insects", "bug garden"],
      ["bird", "Bird", "birds garden"],
      ["recycle", "Recycling", "green waste"],
      ["park", "Park", "outdoors green"],
      ["farm", "Farm", "countryside land"],
    ],
  },
  {
    id: "things",
    label: "Things",
    icons: [
      ["device-mobile", "Phone", "mobile apps device"],
      ["device-tablet", "Tablet", "ipad device"],
      ["desktop", "Computer", "desktop setup device"],
      ["laptop", "Laptop", "computer work"],
      ["keyboard", "Keyboard", "typing input"],
      ["mouse", "Mouse", "pointer input"],
      ["hard-drive", "Storage", "disk backup"],
      ["usb", "USB", "drive stick"],
      ["database", "Database", "data server"],
      ["robot", "Robot", "ai automation bot"],
      ["headphones", "Audio", "music podcast"],
      ["microphone", "Microphone", "record voice"],
      ["music-notes", "Music", "song listening"],
      ["vinyl-record", "Records", "vinyl music"],
      ["radio", "Radio", "listen broadcast"],
      ["guitar", "Guitar", "practice band"],
      ["piano-keys", "Piano", "keys music practice"],
      ["camera", "Photos", "camera pictures"],
      ["video-camera", "Video", "filming record"],
      ["film-slate", "Film", "video watch movies"],
      ["television", "TV", "watch series shows"],
      ["projector-screen", "Projector", "screen presentation"],
      ["game-controller", "Games", "gaming console play"],
      ["puzzle-piece", "Puzzles", "jigsaw game"],
      ["dice-five", "Dice", "board games chance"],
      ["cards", "Card games", "deck play"],
      ["palette", "Art", "design paint creative"],
      ["paint-brush", "Brush", "art paint"],
      ["pen-nib", "Calligraphy", "ink writing"],
      ["scissors", "Crafts", "cut making"],
      ["newspaper", "News", "press reading"],
      ["magnifying-glass", "Search", "find look"],
      ["flashlight", "Torch", "light dark"],
      ["battery-charging", "Power", "battery energy charge"],
      ["lock", "Security", "lock passwords private"],
      ["shield-check", "Protection", "safe secure"],
      ["fingerprint", "Identity", "biometric login"],
      ["wifi-high", "Wi-Fi", "internet network"],
      ["wrench", "Maintenance", "tools fix upkeep"],
      ["shopping-bag", "Shopping", "buy store"],
      ["t-shirt", "Clothes", "wardrobe wear"],
      ["sneaker", "Shoes", "trainers footwear"],
      ["watch", "Watch", "time wear"],
      ["sunglasses", "Sunglasses", "summer wear"],
      ["crown", "Crown", "premium best"],
      ["trophy", "Trophy", "win award"],
      ["medal", "Medal", "award achievement"],
      ["magic-wand", "Magic", "sparkle effects"],
      ["binoculars", "Spotting", "look watch"],
      ["metronome", "Practice", "rhythm timing"],
    ],
  },
  {
    id: "shapes",
    label: "Shapes",
    icons: [
      ["circle", "Circle", "dot shape"],
      ["circle-half", "Half circle", "shape split"],
      ["square", "Square", "shape"],
      ["square-half", "Half square", "shape split"],
      ["triangle", "Triangle", "shape"],
      ["diamond", "Diamond", "shape"],
      ["hexagon", "Hexagon", "shape"],
      ["pentagon", "Pentagon", "shape"],
      ["octagon", "Octagon", "shape"],
      ["shapes", "Shapes", "geometry mixed"],
      ["cube", "Cube", "3d box shape"],
      ["sphere", "Sphere", "3d ball shape"],
      ["cylinder", "Cylinder", "3d shape"],
      ["star-four", "Four-point star", "star shape"],
      ["star-half", "Half star", "rating shape"],
      ["sparkle", "Sparkle", "shine new"],
      ["heart-straight", "Heart", "love shape"],
      ["lightning", "Bolt", "energy fast"],
      ["flag", "Flag", "mark milestone"],
      ["flag-banner", "Banner", "flag mark"],
      ["bookmark-simple", "Bookmark", "save mark"],
      ["seal", "Seal", "badge shape"],
      ["check-circle", "Done", "check complete"],
      ["x-circle", "Cancelled", "no stop"],
      ["plus-circle", "Add", "new plus"],
      ["minus-circle", "Remove", "less minus"],
      ["dot-outline", "Dot", "minimal plain"],
      ["dots-three", "More", "menu ellipsis"],
      ["asterisk", "Asterisk", "star note"],
      ["infinity", "Infinity", "endless loop"],
      ["spiral", "Spiral", "swirl shape"],
      ["yin-yang", "Balance", "harmony shape"],
      ["crosshair-simple", "Crosshair", "aim target"],
      ["radio-button", "Radio", "option select"],
      ["checkerboard", "Checks", "grid pattern"],
    ],
  },
];
