// The curated Phosphor set offered in DoDone's project icon picker.
// Groups mirror the emoji catalogue so the two tabs read the same way.
export const GROUPS = [
  {
    id: "work",
    label: "Work",
    icons: [
      ["briefcase", "Briefcase", "work job business"],
      ["buildings", "Office", "building company"],
      ["chart-bar", "Chart", "report data metrics"],
      ["trend-up", "Growth", "chart up revenue"],
      ["note-pencil", "Notes", "write memo draft"],
      ["clipboard-text", "Clipboard", "list checklist admin"],
      ["folders", "Files", "folder archive"],
      ["push-pin", "Pin", "important sticky"],
      ["calendar-blank", "Calendar", "schedule planning"],
      ["alarm", "Deadline", "alarm time urgent"],
      ["target", "Goal", "target okr focus"],
      ["rocket-launch", "Launch", "ship release startup"],
      ["gear", "Operations", "settings process"],
      ["lightbulb", "Idea", "brainstorm concept"],
      ["handshake", "Meeting", "client partner deal"],
      ["envelope-simple", "Email", "inbox mail message"],
      ["phone", "Calls", "phone ring"],
      ["toolbox", "Toolbox", "maintenance utilities"],
    ],
  },
  {
    id: "study",
    label: "Study",
    icons: [
      ["books", "Books", "reading library study"],
      ["book-open", "Reading", "book chapter"],
      ["graduation-cap", "School", "university course degree"],
      ["pencil-simple", "Writing", "essay draft author"],
      ["brain", "Learning", "brain think memory"],
      ["microscope", "Research", "science lab"],
      ["flask", "Experiment", "lab test chemistry"],
      ["calculator", "Maths", "numbers sums"],
      ["planet", "Astronomy", "space explore telescope"],
      ["globe-hemisphere-west", "Languages", "globe world"],
      ["backpack", "Backpack", "school class"],
      ["code", "Code", "dev programming"],
    ],
  },
  {
    id: "home",
    label: "Home",
    icons: [
      ["house", "Home", "house personal"],
      ["armchair", "Living room", "sofa lounge furniture"],
      ["bed", "Bedroom", "bed sleep"],
      ["shower", "Bathroom", "shower clean"],
      ["broom", "Cleaning", "chores tidy"],
      ["washing-machine", "Laundry", "washing clothes"],
      ["hand-soap", "Washing up", "soap dishes clean"],
      ["hammer", "DIY", "hammer repair build"],
      ["screwdriver", "Fixing", "repair tools"],
      ["potted-plant", "Plants", "houseplant garden water"],
      ["package", "Moving", "box packing storage"],
      ["key", "Keys", "access landlord rent"],
      ["door", "Doors", "room entry"],
      ["receipt", "Bills", "receipt utilities admin"],
    ],
  },
  {
    id: "people",
    label: "People",
    icons: [
      ["users-three", "Family", "household kids parents"],
      ["baby", "Baby", "child kids newborn"],
      ["user", "Person", "someone me friend"],
      ["hand-waving", "Catch-ups", "hello friends social"],
      ["chat-circle-dots", "Conversations", "chat talk message"],
      ["heart", "Love", "heart partner relationship"],
      ["confetti", "Celebration", "party event fun"],
      ["gift", "Gifts", "present birthday"],
      ["cake", "Birthdays", "cake anniversary"],
      ["envelope-open", "Cards", "letter note thanks"],
      ["dog", "Dog", "pet puppy walk"],
      ["cat", "Cat", "pet kitten"],
    ],
  },
  {
    id: "health",
    label: "Health",
    icons: [
      ["person-simple-run", "Running", "exercise cardio jog"],
      ["person-simple-tai-chi", "Meditation", "yoga calm mindful"],
      ["barbell", "Gym", "weights lifting strength"],
      ["person-simple-bike", "Cycling", "bike ride"],
      ["person-simple-swim", "Swimming", "pool swim"],
      ["heartbeat", "Fitness", "health pulse"],
      ["soccer-ball", "Football", "soccer sport team"],
      ["basketball", "Basketball", "sport hoops"],
      ["tennis-ball", "Tennis", "sport racket"],
      ["stethoscope", "Doctor", "medical appointment"],
      ["pill", "Medication", "pills pharmacy"],
      ["tooth", "Dentist", "teeth appointment"],
      ["moon", "Sleep", "rest bedtime night"],
      ["bowl-food", "Eating well", "salad diet healthy"],
    ],
  },
  {
    id: "food",
    label: "Food",
    icons: [
      ["cooking-pot", "Cooking", "kitchen recipe meal"],
      ["shopping-cart", "Groceries", "shopping supermarket"],
      ["fork-knife", "Meals", "dinner eating restaurant"],
      ["carrot", "Vegetables", "veg greens"],
      ["bread", "Baking", "bread oven"],
      ["coffee", "Coffee", "cafe morning break"],
      ["beer-stein", "Drinks", "bar evening pub"],
      ["pizza", "Takeaway", "pizza delivery"],
      ["cookie", "Treats", "dessert sweet"],
      ["wine", "Wine", "drinks evening"],
      ["snowflake", "Freezer", "ice cold meal prep"],
      ["egg", "Breakfast", "eggs morning"],
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icons: [
      ["airplane-tilt", "Flights", "plane travel trip"],
      ["suitcase-rolling", "Packing", "luggage suitcase trip"],
      ["map-trifold", "Trip planning", "map itinerary route"],
      ["car", "Driving", "car road trip"],
      ["train", "Trains", "rail commute"],
      ["bus", "Bus", "transit commute"],
      ["bicycle", "Bike", "cycling commute"],
      ["gas-pump", "Fuel", "petrol gas car"],
      ["buildings", "Hotels", "stay booking accommodation"],
      ["ticket", "Tickets", "booking event entry"],
      ["island", "Holiday", "beach island vacation"],
      ["tent", "Camping", "tent outdoors"],
      ["mountains", "Mountains", "hiking outdoors ski"],
      ["globe", "World", "international abroad"],
    ],
  },
  {
    id: "money",
    label: "Money",
    icons: [
      ["money", "Money", "cash savings budget"],
      ["credit-card", "Card", "payment spending credit"],
      ["coins", "Savings", "coin invest pension"],
      ["bank", "Bank", "account mortgage finance"],
      ["wallet", "Wallet", "spending pocket"],
      ["trend-down", "Expenses", "chart down costs"],
      ["tag", "Deals", "price sale"],
      ["piggy-bank", "Budget", "saving goal"],
      ["invoice", "Invoices", "billing receipt"],
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icons: [
      ["plant", "Growing", "seedling start garden"],
      ["tree", "Tree", "garden outdoors nature"],
      ["flower", "Blossom", "flower spring"],
      ["leaf", "Autumn", "leaves fall season"],
      ["sun", "Sun", "summer weather morning"],
      ["moon-stars", "Night", "moon evening"],
      ["star", "Star", "favourite highlight special"],
      ["cloud-sun", "Weather", "cloud forecast"],
      ["snowflake", "Winter", "snow cold season"],
      ["fire", "Hot", "fire streak urgent"],
      ["waves", "Water", "sea wave ocean"],
      ["fish", "Fish", "aquarium pet sea"],
    ],
  },
  {
    id: "things",
    label: "Things",
    icons: [
      ["device-mobile", "Phone", "mobile apps device"],
      ["desktop", "Computer", "desktop setup device"],
      ["laptop", "Laptop", "computer work"],
      ["headphones", "Audio", "music podcast"],
      ["camera", "Photos", "camera pictures"],
      ["game-controller", "Games", "gaming console play"],
      ["guitar", "Music", "guitar practice band"],
      ["palette", "Art", "design paint creative"],
      ["film-slate", "Film", "video watch movies"],
      ["television", "TV", "watch series shows"],
      ["lock", "Security", "lock passwords private"],
      ["battery-charging", "Power", "battery energy charge"],
      ["wrench", "Maintenance", "tools fix upkeep"],
      ["shopping-bag", "Shopping", "buy store"],
    ],
  },
  {
    id: "shapes",
    label: "Shapes",
    icons: [
      ["circle", "Circle", "dot shape"],
      ["square", "Square", "shape"],
      ["triangle", "Triangle", "shape"],
      ["diamond", "Diamond", "shape"],
      ["hexagon", "Hexagon", "shape"],
      ["star-four", "Sparkle", "star shape"],
      ["heart-straight", "Heart", "love shape"],
      ["lightning", "Bolt", "energy fast"],
      ["flag", "Flag", "mark milestone"],
      ["bookmark-simple", "Bookmark", "save mark"],
      ["check-circle", "Done", "check complete"],
      ["dot-outline", "Dot", "minimal plain"],
    ],
  },
];
