/**
 * Emits packages/shared/src/phosphor-data.generated.ts from @phosphor-icons/core.
 *
 *   cd tools/phosphor
 *   npm pack @phosphor-icons/core && tar xzf phosphor-icons-core-*.tgz
 *   node emit.mjs
 *
 * `catalogue.mjs` beside this is the curated list — the icons the picker
 * offers, grouped the way the emoji catalogue is. Adding one there and
 * re-running is the whole workflow; the generated file is never hand-edited.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { EXTRA, GROUPS } from "./catalogue.mjs";

const ROOT = new URL(".", import.meta.url).pathname;
const VERSION = process.env.PHOSPHOR_VERSION ?? "2.1.1";
// Point this at an unpacked @phosphor-icons/core. From this directory:
//   npm pack @phosphor-icons/core && tar xzf phosphor-icons-core-*.tgz
const ASSETS = process.env.PHOSPHOR_ASSETS ?? join(ROOT, "package/assets");
const OUT = join(ROOT, "../../packages/shared/src/phosphor-data.generated.ts");

const WEIGHTS = { bold: "bold", fill: "fill", duotone: "duotone" };

/** Pull the `d` attributes out of a Phosphor asset, in document order. */
function paths(weight, name) {
  const file = join(ASSETS, weight, `${name}-${weight}.svg`);
  const raw = readFileSync(file, "utf8");
  const out = [];
  const re = /<path\b([^>]*)\/>/g;
  let m;
  while ((m = re.exec(raw))) {
    const attrs = m[1];
    const d = attrs.match(/\sd="([^"]+)"/)?.[1];
    if (!d) continue;
    const opacity = attrs.match(/opacity="([^"]+)"/)?.[1];
    out.push({ d, opacity: opacity ? Number(opacity) : undefined });
  }
  if (out.length === 0) throw new Error(`no paths in ${file}`);
  return out;
}

// Every icon named anywhere in the catalogue, once, plus the few the app draws
// without offering. `EXTRA` reaches PHOSPHOR_PATHS but never PHOSPHOR_CATALOGUE
// — the picker's grid is built from `groups` below.
const names = [
  ...new Set([...GROUPS.flatMap((g) => g.icons.map((i) => i[0])), ...EXTRA]),
].sort();

const data = {};
for (const name of names) {
  const entry = {};
  for (const w of Object.keys(WEIGHTS)) {
    const p = paths(w, name);
    if (w === "duotone") {
      // Duotone is exactly two layers: a 20%-opacity solid behind a line.
      const secondary = p.find((x) => x.opacity !== undefined);
      const primary = p.filter((x) => x.opacity === undefined).map((x) => x.d);
      if (!secondary) throw new Error(`duotone ${name} has no faded layer`);
      entry.duotone = { back: secondary.d, front: primary };
    } else {
      entry[w] = p.map((x) => x.d);
    }
  }
  data[name] = entry;
}

const groups = GROUPS.map((g) => ({
  id: g.id,
  label: g.label,
  icons: g.icons.map(([name, label, keywords]) => ({
    name,
    label,
    keywords: keywords.split(" "),
  })),
}));

const banner = `/**
 * GENERATED FILE — do not edit by hand.
 *
 * Phosphor ${VERSION} (MIT) path data for the curated set offered in the project
 * icon picker plus the few icons fixed UI draws (\`EXTRA\`), in the three weights
 * the app exposes. Regenerated by
 * \`tools/phosphor/emit.mjs\` against @phosphor-icons/core; the curated list
 * itself lives in \`tools/phosphor/catalogue.mjs\` beside it.
 *
 * Only the \`d\` attributes are kept. Every Phosphor icon is drawn on a 256×256
 * grid with no strokes — the shapes are filled — so a renderer needs nothing
 * from the source beyond these strings and \`viewBox="0 0 256 256"\`.
 *
 * ${names.length} icons × 3 weights; ${groups.reduce((n, g) => n + g.icons.length, 0)} of them
 * offered in the picker.
 */

/** Two layers: a 20%-opacity solid behind the line work. */
export interface PhosphorDuotonePaths {
  back: string;
  front: readonly string[];
}

export interface PhosphorIconPaths {
  bold: readonly string[];
  fill: readonly string[];
  duotone: PhosphorDuotonePaths;
}

export interface PhosphorCatalogueIcon {
  name: string;
  label: string;
  keywords: readonly string[];
}

export interface PhosphorCatalogueGroup {
  id: string;
  label: string;
  icons: readonly PhosphorCatalogueIcon[];
}

export const PHOSPHOR_VIEW_BOX = "0 0 256 256";

export const PHOSPHOR_PATHS: Record<string, PhosphorIconPaths> = ${JSON.stringify(data, null, 2)};

export const PHOSPHOR_CATALOGUE: readonly PhosphorCatalogueGroup[] = ${JSON.stringify(groups, null, 2)};
`;

writeFileSync(OUT, banner);
const kb = (banner.length / 1024).toFixed(0);
console.log(`wrote ${OUT}`);
console.log(`${names.length} icons, ${kb}KB`);

// Per-weight weight, so the bundle cost is visible rather than assumed.
for (const w of ["bold", "fill", "duotone"]) {
  const bytes = names.reduce((n, name) => n + JSON.stringify(data[name][w]).length, 0);
  console.log(`  ${w.padEnd(8)} ${(bytes / 1024).toFixed(0)}KB`);
}
