/**
 * Config plugin: adds a translucent native Android activity (`QuickAddActivity`)
 * that hosts the "QuickAdd" JS root over the live home screen.
 *
 * The 1x1 quick-add widget taps `dodoneadd://open`. MainActivity (expo-router)
 * only claims the `dodone` scheme, so the dedicated `dodoneadd` scheme resolves
 * to exactly this activity — no disambiguation chooser, no main-app launch.
 *
 * Three mods:
 *   1. withDangerousMod  — write QuickAddActivity.kt into the app's java package
 *   2. withAndroidManifest — register the <activity> with the translucent theme
 *      and a VIEW intent-filter for the dodoneadd scheme
 *   3. withAndroidStyles  — define Theme.App.QuickAddTranslucent (parent AppTheme)
 *
 * Continuous Native Generation regenerates all three on every `expo prebuild`.
 */
const {
  withDangerousMod,
  withAndroidManifest,
  withAndroidStyles,
  AndroidConfig,
  createRunOncePlugin,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const ACTIVITY_NAME = '.QuickAddActivity';
const THEME_NAME = 'Theme.App.QuickAddTranslucent';
const SCHEME = 'dodoneadd';

function activityKotlin(pkg) {
  return `package ${pkg}

import android.os.Bundle
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import expo.modules.ReactActivityDelegateWrapper

/**
 * Translucent activity hosting the "QuickAdd" JS root. Launched by the 1x1
 * home-screen widget via the dedicated \`${SCHEME}://\` scheme so it floats over
 * the live home screen without bringing up MainActivity. Runs in its own task
 * (taskAffinity="" in the manifest) so BackHandler.exitApp() from JS finishes
 * only this surface and returns to the launcher. Generated by
 * plugins/withQuickAddActivity.js — do not edit by hand.
 */
class QuickAddActivity : ReactActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    // Do not restore MainActivity's saved state into this lightweight surface.
    super.onCreate(null)
  }

  override fun getMainComponentName(): String = "QuickAdd"

  override fun createReactActivityDelegate(): ReactActivityDelegate =
    ReactActivityDelegateWrapper(
      this,
      BuildConfig.IS_NEW_ARCHITECTURE_ENABLED,
      object : DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled) {}
    )
}
`;
}

const withQuickAddSource = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const pkg = cfg.android && cfg.android.package;
      if (!pkg) {
        throw new Error(
          'withQuickAddActivity: expo config is missing android.package'
        );
      }
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'java',
        ...pkg.split('.')
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(dir, 'QuickAddActivity.kt'),
        activityKotlin(pkg),
        'utf8'
      );
      return cfg;
    },
  ]);

const withQuickAddManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(
      cfg.modResults
    );
    mainApplication.activity = mainApplication.activity || [];
    const exists = mainApplication.activity.some(
      (a) => a.$ && a.$['android:name'] === ACTIVITY_NAME
    );
    if (!exists) {
      mainApplication.activity.push({
        $: {
          'android:name': ACTIVITY_NAME,
          'android:exported': 'true',
          'android:theme': `@style/${THEME_NAME}`,
          'android:launchMode': 'singleTask',
          'android:taskAffinity': '',
          'android:excludeFromRecents': 'true',
          // Without this the activity inherits the platform default
          // (adjustPan/adjustUnspecified), so showing the IME PANS the whole
          // translucent window up — on top of the composer's own keyboard
          // offset, which made the sheet jump around above the keyboard.
          // adjustResize + edge-to-edge means the window holds still and the
          // composer alone owns the offset (see QuickAddComposer). It also
          // matches MainActivity, so the in-app quick-add behaves identically.
          'android:windowSoftInputMode': 'adjustResize',
          'android:configChanges':
            'keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode',
        },
        'intent-filter': [
          {
            action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
            category: [
              { $: { 'android:name': 'android.intent.category.DEFAULT' } },
              { $: { 'android:name': 'android.intent.category.BROWSABLE' } },
            ],
            data: [{ $: { 'android:scheme': SCHEME } }],
          },
        ],
      });
    }
    return cfg;
  });

// Translucent theme so the home-screen wallpaper/icons show through; the JS
// root draws its own dim scrim. Parent AppTheme is always emitted by Expo and
// tracks edge-to-edge / DayNight changes.
const STYLE_ITEMS = [
  { name: 'android:windowIsTranslucent', value: 'true' },
  { name: 'android:windowBackground', value: '@android:color/transparent' },
  { name: 'android:windowContentOverlay', value: '@null' },
  { name: 'android:windowNoTitle', value: 'true' },
  { name: 'android:windowActionBar', value: 'false' },
  { name: 'android:windowAnimationStyle', value: '@android:style/Animation.Dialog' },
];

const withQuickAddStyle = (config) =>
  withAndroidStyles(config, (cfg) => {
    const parent = { name: THEME_NAME, parent: 'AppTheme' };
    for (const { name, value } of STYLE_ITEMS) {
      cfg.modResults = AndroidConfig.Styles.setStylesItem({
        xml: cfg.modResults,
        parent,
        item: { _: value, $: { name } },
      });
    }
    return cfg;
  });

const withQuickAddActivity = (config) =>
  withQuickAddStyle(withQuickAddManifest(withQuickAddSource(config)));

module.exports = createRunOncePlugin(
  withQuickAddActivity,
  'withQuickAddActivity',
  '1.0.0'
);
