/**
 * Config plugin: Android **app shortcuts** — the four quick actions in the
 * launcher's long-press menu, each with a "+" that pins it to the home screen
 * as a plain icon (Todoist's Add task / Search / Today / Upcoming).
 *
 * These are not widgets. A pinned shortcut occupies exactly one launcher cell
 * and is drawn by the launcher itself, so it lines up with the app icons around
 * it — which is the whole point of asking for them over a 1x1 widget.
 *
 * Static shortcuts (`res/xml/shortcuts.xml` + a `meta-data` pointer on the
 * launcher activity) rather than dynamic ones: they exist from install, before
 * the app has ever run, and cost no native code at runtime.
 *
 * Four mods:
 *   1. withDangerousMod    — write res/xml/shortcuts.xml and the icon drawables
 *   2. withStringsXml      — the labels (a static shortcut's labels *must* be
 *                            string resources; a literal is silently dropped)
 *   3. withAndroidManifest — meta-data on the launcher activity pointing at
 *                            @xml/shortcuts
 *
 * Continuous Native Generation regenerates all of it on every `expo prebuild`.
 */
const {
  withDangerousMod,
  withAndroidManifest,
  withStringsXml,
  AndroidConfig,
  createRunOncePlugin,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** Indigo-500 — the same accent the adaptive launcher icon sits on. */
const ICON_BACKGROUND = '#6366F1';
const ICON_FOREGROUND = '#FFFFFF';
const BACKGROUND_DRAWABLE = 'dodone_shortcut_background';

/**
 * The quick actions, in the order the launcher lists them.
 *
 * `activity` names the component the shortcut launches:
 *   - 'quick-add' — the translucent QuickAddActivity, so the composer floats
 *     over the live home screen exactly as the 1x1 widget does. It is targeted
 *     by class here, so the dedicated `dodoneadd` scheme is belt-and-braces.
 *   - everything else — MainActivity, which hands the URI to expo-router.
 *
 * `glyph` is a Material icon path in a 24x24 space; drawGlyph scales it into
 * the 108x108 adaptive-icon viewport.
 */
const SHORTCUTS = [
  {
    id: 'quick-add',
    shortLabel: 'Add task',
    longLabel: 'Add a task to DoDone',
    activity: 'QuickAddActivity',
    data: 'dodoneadd://open',
    glyph: 'M19,13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z',
  },
  {
    id: 'search',
    shortLabel: 'Search',
    longLabel: 'Search your tasks',
    activity: 'MainActivity',
    data: 'dodone://search',
    glyph:
      'M15.5,14h-0.79l-0.28,-0.27C15.41,12.59 16,11.11 16,9.5 16,5.91 13.09,3 9.5,3S3,5.91 3,9.5 5.91,16 9.5,16c1.61,0 3.09,-0.59 4.23,-1.57l0.27,0.28v0.79l5,4.99L20.49,19l-4.99,-5zM9.5,14C7.01,14 5,11.99 5,9.5S7.01,5 9.5,5 14,7.01 14,9.5 11.99,14 9.5,14z',
  },
  {
    id: 'today',
    shortLabel: 'Today',
    longLabel: 'Tasks scheduled for today',
    activity: 'MainActivity',
    data: 'dodone://today',
    glyph:
      'M19,3h-1V1h-2v2H8V1H6v2H5c-1.11,0 -1.99,0.9 -1.99,2L3,19c0,1.1 0.89,2 2,2h14c1.1,0 2,-0.9 2,-2V5c0,-1.1 -0.9,-2 -2,-2zM19,19H5V8h14v11zM7,10h5v5H7z',
  },
  {
    id: 'upcoming',
    shortLabel: 'Upcoming',
    longLabel: 'Tasks for the days ahead',
    activity: 'MainActivity',
    data: 'dodone://upcoming',
    glyph:
      'M9,11H7v2h2v-2zM13,11h-2v2h2v-2zM17,11h-2v2h2v-2zM19,4h-1V2h-2v2H8V2H6v2H5c-1.11,0 -1.99,0.9 -1.99,2L3,20c0,1.1 0.89,2 2,2h14c1.1,0 2,-0.9 2,-2V6c0,-1.1 -0.9,-2 -2,-2zM19,20H5V9h14v11z',
  },
];

const iconName = (id) => `ic_shortcut_${id.replace(/-/g, '_')}`;
const shortLabelRes = (id) => `dodone_shortcut_${id.replace(/-/g, '_')}_short`;
const longLabelRes = (id) => `dodone_shortcut_${id.replace(/-/g, '_')}_long`;

/**
 * The 24x24 glyph, scaled 2.5x and centred in the 108x108 viewport. That lands
 * it in 24..84 — inside the 18..90 safe zone every launcher mask leaves alone,
 * so no mask shape can clip it.
 */
function drawGlyph(glyph) {
  return `  <group android:scaleX="2.5" android:scaleY="2.5" android:translateX="24" android:translateY="24">
    <path android:fillColor="${ICON_FOREGROUND}" android:pathData="${glyph}" />
  </group>`;
}

/** Adaptive-icon foreground: the glyph alone, on transparency. */
function foregroundVector(glyph) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidShortcuts.js — do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${drawGlyph(glyph)}
</vector>
`;
}

/**
 * Pre-API-26 fallback: the glyph on a filled circle, since those launchers draw
 * a shortcut icon as-is with no mask. API 26+ picks the adaptive icon in
 * drawable-anydpi-v26 instead and masks it to match the app icons beside it.
 */
function legacyVector(glyph) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidShortcuts.js — do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <path
      android:fillColor="${ICON_BACKGROUND}"
      android:pathData="M54,0 A54,54 0 1 0 54,108 A54,54 0 1 0 54,0 Z" />
${drawGlyph(glyph)}
</vector>
`;
}

function adaptiveIcon(id) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidShortcuts.js — do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@drawable/${BACKGROUND_DRAWABLE}" />
  <foreground android:drawable="@drawable/${iconName(id)}_fg" />
</adaptive-icon>
`;
}

const backgroundDrawable = () => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidShortcuts.js — do not edit by hand. -->
<color xmlns:android="http://schemas.android.com/apk/res/android"
    android:color="${ICON_BACKGROUND}" />
`;

/**
 * res/xml/shortcuts.xml. Every intent is explicit (targetPackage +
 * targetClass) — a static shortcut with an implicit intent never launches — and
 * carries the deep link as its data URI, which is what expo-linking reads back
 * out via getInitialURL.
 */
function shortcutsXml(pkg) {
  const entries = SHORTCUTS.map(
    (s) => `  <shortcut
      android:shortcutId="${s.id}"
      android:enabled="true"
      android:icon="@drawable/${iconName(s.id)}"
      android:shortcutShortLabel="@string/${shortLabelRes(s.id)}"
      android:shortcutLongLabel="@string/${longLabelRes(s.id)}">
    <intent
        android:action="android.intent.action.VIEW"
        android:targetPackage="${pkg}"
        android:targetClass="${pkg}.${s.activity}"
        android:data="${s.data}" />
  </shortcut>`
  ).join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidShortcuts.js — do not edit by hand. -->
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
${entries}
</shortcuts>
`;
}

const withShortcutResources = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const pkg = cfg.android && cfg.android.package;
      if (!pkg) {
        throw new Error(
          'withAndroidShortcuts: expo config is missing android.package'
        );
      }
      const res = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res'
      );
      const xmlDir = path.join(res, 'xml');
      const drawableDir = path.join(res, 'drawable');
      const adaptiveDir = path.join(res, 'drawable-anydpi-v26');
      for (const dir of [xmlDir, drawableDir, adaptiveDir]) {
        fs.mkdirSync(dir, { recursive: true });
      }

      fs.writeFileSync(
        path.join(xmlDir, 'shortcuts.xml'),
        shortcutsXml(pkg),
        'utf8'
      );
      fs.writeFileSync(
        path.join(drawableDir, `${BACKGROUND_DRAWABLE}.xml`),
        backgroundDrawable(),
        'utf8'
      );
      for (const s of SHORTCUTS) {
        const name = iconName(s.id);
        fs.writeFileSync(
          path.join(drawableDir, `${name}.xml`),
          legacyVector(s.glyph),
          'utf8'
        );
        fs.writeFileSync(
          path.join(drawableDir, `${name}_fg.xml`),
          foregroundVector(s.glyph),
          'utf8'
        );
        fs.writeFileSync(
          path.join(adaptiveDir, `${name}.xml`),
          adaptiveIcon(s.id),
          'utf8'
        );
      }
      return cfg;
    },
  ]);

const withShortcutStrings = (config) =>
  withStringsXml(config, (cfg) => {
    const items = [];
    for (const s of SHORTCUTS) {
      items.push(
        AndroidConfig.Resources.buildResourceItem({
          name: shortLabelRes(s.id),
          value: s.shortLabel,
          translatable: true,
        }),
        AndroidConfig.Resources.buildResourceItem({
          name: longLabelRes(s.id),
          value: s.longLabel,
          translatable: true,
        })
      );
    }
    cfg.modResults = AndroidConfig.Strings.setStringItem(items, cfg.modResults);
    return cfg;
  });

/**
 * The meta-data has to sit on the activity carrying the LAUNCHER intent-filter
 * — that is the icon being long-pressed — even for the shortcut that launches
 * QuickAddActivity instead.
 */
const withShortcutManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const mainActivity = AndroidConfig.Manifest.getMainActivityOrThrow(
      cfg.modResults
    );
    mainActivity['meta-data'] = mainActivity['meta-data'] || [];
    const existing = mainActivity['meta-data'].find(
      (m) => m.$ && m.$['android:name'] === 'android.app.shortcuts'
    );
    if (existing) {
      existing.$['android:resource'] = '@xml/shortcuts';
    } else {
      mainActivity['meta-data'].push({
        $: {
          'android:name': 'android.app.shortcuts',
          'android:resource': '@xml/shortcuts',
        },
      });
    }
    return cfg;
  });

const withAndroidShortcuts = (config) =>
  withShortcutManifest(withShortcutStrings(withShortcutResources(config)));

module.exports = createRunOncePlugin(
  withAndroidShortcuts,
  'withAndroidShortcuts',
  '1.0.0'
);

// Exposed for the unit test, which asserts the generated XML rather than
// running a prebuild.
module.exports.SHORTCUTS = SHORTCUTS;
module.exports.shortcutsXml = shortcutsXml;
module.exports.legacyVector = legacyVector;
module.exports.foregroundVector = foregroundVector;
module.exports.adaptiveIcon = adaptiveIcon;
module.exports.iconName = iconName;
module.exports.shortLabelRes = shortLabelRes;
module.exports.longLabelRes = longLabelRes;
